### PR TITLE
Newsweek Replica Project with Bootstrap

### PR DESCRIPTION
**Pull request by nusretbutunay**
This project consists of building a responsive clone of the Newsweek web site using bootstrap.

In this project:

We took a mobile first approach and started styling for the smallest screen size
We used mainly bootstrap classes instead of pure css.

### CODE REVIEW

**Review by elmejdki — CHANGES_REQUESTED** [review]
# status requires changes :recycle: 
## Great job guys you have made a really good clone :clap: :100:, it responsive and all but you need to make just some minor changes :hammer: :toolbox: :wrench:  to get it approved. :checkered_flag: 

- [x] Fix the navbar submenu items they are breaking, you can use flex-shrink-0 class and put the search input on the right somehow:
image

- [x] Fix the subscribe and the newsletter section cause they should be aligned but they aren't
### clone:
image

### original:
image

- [x] On tablet view you have a lot of space between subscribe and newsletter fix it please:
image

- [x] Fix the opinion form make it a little bit wider on mobile view:
### clone:
image
### original:
image

- [x] On mobile screen center the content of both the newsletter and subscribe sections:
### clone:
image

### original:
image

- [x] I have noticed that you are having more space on the right than the left for the whole website in the mobile view fix that also:
image

### Please make all the required changes before you request another code review.
# Happy Coding :tophat:

**Review by voscarmv — CHANGES_REQUESTED** [review]
# Impressive work, team! 🖥️ 👀 ✨ 
## However, some changes are still required... 🧰 🔨 🔧 

- When shrinking the page, the image from the NEWSLETTER section appears stretched. Please fix this.
image

### Submit these changes and request a new code review! 😄 👍 
### Questions or comments? Reach me on [Twitter](https://twitter.com/voscarmv) or [LinkedIn](https://linkedin.com/in/oscar-mier) 🧑‍💻🗨️🧑‍💻 
# Happy Hacking! 🧠 ⌨️ 🖱️ 🖥️

**Review by christianotieno — CHANGES_REQUESTED** [review]
# **CHANGES REQUIRED** :warning:
Hey Team :wave:
Good job so far! :tada: We still have some few changes to do before we proceed (see review comment).
If you have any questions, let me know here or on slack and I will be glad to clarify with you. You can also reach me and connect with me on my social media or email.*** :eyes:
##
## Main Page Structure
|[Source Page](https://www.newsweek.com/)|[Clone Page](https://raw.githack.com/nusretbutunay/newsweek_replica/newsweek/index.html)|
|:---:|:---:|
|source|clone|
- [x] This being a responsive project. We need to make sure nothing is messed up. From the difference above the general structure of the page ought to be properly centred as it appears in the source page.

## NavBar
|[Source Page](https://www.newsweek.com/)|[ClonePage](https://raw.githack.com/nusretbutunay/newsweek_replica/newsweek/index.html)|
|:---:|:---:|
|navbar|navbar-clone|
- The navlinks in the navbar are not properly aligned. Kindly let's fix this.
## In the magazine section
|[Source Page](https://www.newsweek.com/)|[ClonePage](https://raw.githack.com/nusretbutunay/newsweek_replica/newsweek/index.html)|
|:---:|:---:|
|in-the-magazine|in-the-magazine-clone|
- [x] This section has a space that is shoeing between the higleted area that should not be present. Let's fix this section.
## Us, World... etc. Section
|[Source Page](https://www.newsweek.com/)|[ClonePage](https://raw.githack.com/nusretbutunay/newsweek_replica/newsweek/index.html)|
|:---:|:---:|
|us-world|us-world-clone|
- [x] Just as with the previously suggested changes in the `in the magazine` section, Let's work on these sections as well. Space is also shoeing on medium screens as well. 
##
- When you have made the specified changes, please submit another code review. Thank you!
*Happy coding :smile:,*
**[Christian Otieno](https://github.com/ChristianOtieno)**
[Twitter](https://twitter.com/iamchrisotieno) [linkedin](https://www.linkedin.com/in/christianotieno/) [GitLab](https://gitlab.com/christianotieno)
---
*P.S. all requested changes not marked by [OPTIONAL] or are not positive comments are **REQUIRED***

**Review by BrittanyBlake — CHANGES_REQUESTED** [review]
### Status: Changes Required  🏗️ 🔨 
****
### Hello @nusretbutunay and @rahalrazika   👋 
Your project looks amazing!👍 I can see that you are working diligently in implementing the feedback you have been receiving and you are doing a phenomenal job!🎖️ 🌟 You are almost done! 💪 There is just one small issue that I feel needs to be resolved before you can move on: ⬇️ 
****

- [x] On the medium screen in the Featured slideshows sections (US, World, Business, etc.) the article images appear stretched. Please compare your clone with the original page and fix this.
Your clone 👇 
Screen Shot 2020-07-02 at 6 58 04 PM
The original page 👇 
Screen Shot 2020-07-02 at 6 59 30 PM

****
### Kindly make the required changes and resubmit for a new code review once you are ready 🙏


Good Luck and Happy Coding 🍀 👩🏾‍💻

_P.S. If you have any questions about my review or need help, you can message me on slack (@ Brittany Blake)._

**Review by tirthajyoti-ghosh — CHANGES_REQUESTED** [review]
# Status: Changes required 🛑

## Hello team 👋. Your project looks impressive and you have done a great job implementing the changes.

### But we need to work on some changes.

- Please fix this 👇
Annotation 2020-07-02 231633

- Please decrease the size 👇

image

image

Apply these changes and request another review.

Happy coding 👨‍💻

**Review by christianotieno — APPROVED** [review]
# PROJECT APPROVED :champagne:
Excellent job on this project guys. :fireworks: Keep it up.
##
***All the required tasks have been fulfilled in this project. I will go ahead and mark this as complete.***
- Congratulations on the splendid job Team! :+1:
- You can now merge these changes.
- I wish you all the very best in your next tasks 🥇 
##
Happy coding :smile:
**[Christian Otieno](https://github.com/ChristianOtieno)**
[Twitter](https://twitter.com/iamchrisotieno) [linkedin](https://www.linkedin.com/in/christianotieno/) [GitLab](https://gitlab.com/christianotieno)

**Pull request merged**
